window.catalogoPuestos = {
      "Dirección General": ["Auxiliar de Atención Ciudadana",
  "Auxiliar de Concertación Ciudadana",
  "Coordinador de Atención Ciudadana",
  "Coordinador de Concertación Ciudadana",
  "Coordinador de Imagen Institucional",
  "Coordinador de Vinculación",
  "Director General",
  "Jefe de Análisis de Datos",
  "Jefe de Comunicación Social",
  "Jefe de Oficina",
  "Mensajero",
  "Secretaria Particular",
  "Secretaria Técnica",
  "Unidad de Correspondencia A",
  "Unidad de Correspondencia B"],
      "Gerencia de Atención a Usuarios": ["Auxiliar Administrativo B",
  "Auxiliar de Atención Usuarios A",
  "Auxiliar de Atención Usuarios B",
  "Auxiliar de Atención Usuarios C",
  "Auxiliar de Campo, Tomas y Medidores A",
  "Auxiliar de Campo, Tomas y Medidores B",
  "Auxiliar de Campo, Tomas y Medidores C",
  "Auxiliar de Campo, Tomas y Medidores D",
  "Auxiliar de Campo, Tomas y Medidores E",
  "Auxiliar de Campo, Tomas y Medidores F",
  "Auxiliar de Cobranza A",
  "Auxiliar de Cobranza B",
  "Auxiliar de Cobranza C",
  "Auxiliar de Contratos A",
  "Auxiliar de Contratos B",
  "Auxiliar de Contratos C",
  "Auxiliar de Contratos D",
  "Auxiliar de Contratos E",
  "Auxiliar de Contratos F",
  "Coordinador Administrativo B",
  "Coordinador Administrativo C",
  "Coordinador Administrativo D",
  "Coordinador de Factibilidad de Servicios",
  "Coordinador de Padrón de Usuarios y Soporte Técnico",
  "Coordinador Técnico B",
  "Coordinador Técnico C",
  "Director de Atención a Usuarios Zona A",
  "Director de Atención a Usuarios Zona B",
  "Gerente de Atención a Usuarios",
  "Jefe de Zona 1-Fuentes /SADASI",
  "Jefe de Zona 2-Rancho Don Antonio",
  "Jefe de Zona 3-Haciendas de Tizayuca",
  "Jefe de Zona 4-Oficinas Centrales",
  "Jefe de Zona 5-Alameda",
  "Jefe de Zona 6- Móvil",
  "Promotor A",
  "Promotor B",
  "Verificador E",
  "Verificador F",
  "Verificador G"],
      "Gerencia de Hacienda Pública": ["Analista Financiero",
  "Asistente Particular",
  "Auxiliar Administrativo A",
  "Auxiliar de Seguimiento de Personal",
  "Auxiliar de Servicios",
  "Auxiliar de Servicios Generales A",
  "Auxiliar de Servicios Generales B",
  "Coordinador de Adjudicaciones y Licitaciones",
  "Coordinador de Adquisiciones",
  "Coordinador de Almacén",
  "Coordinador de Concialiación Contable",
  "Coordinador de Egresos",
  "Coordinador de Expedientes Unitarios",
  "Coordinador de Formación Continua",
  "Coordinador de Nomina",
  "Coordinador de Patrimonio",
  "Coordinador de Riesgos Laborales",
  "Coordinador de Servicios Generales",
  "Coordinador de Tecnologías de la Información",
  "Coordinador Fiscal",
  "Coordinador General de Recaudación",
  "Director de Administración",
  "Director de Finanzas",
  "Director de Recursos Humanos",
  "Gerente de Hacienda Pública",
  "Jefe de Contabilidad y Presupuestos",
  "Jefe de Cuenta Pública",
  "Jefe de Nomina",
  "Jefe de Recursos Materiales",
  "Jefe de Selección, Seguimiento y Formación Continua"],
      "Gerencia de Infraestructura y Patrimonio Hídrico": ["Auxiliar Administrativo C",
  "Auxiliar Administrativo D",
  "Auxiliar de Mantenimiento A",
  "Auxiliar de Mantenimiento B",
  "Auxiliar de Mantenimiento C",
  "Auxiliar de Seguimiento a Reportes",
  "Auxiliar General",
  "Ayudante de Fontanería de Agua Potable A",
  "Ayudante de Fontanería de Agua Potable B",
  "Ayudante de Fontanería de Agua Potable C",
  "Ayudante de Fontanería de Agua Potable D",
  "Ayudante General A",
  "Ayudante General B",
  "Ayudante General C",
  "Ayudante General D",
  "Ayudante General E",
  "Ayudante General F",
  "Coordinador Administrativo A",
  "Coordinador de Cuadrilla de Agua Potable A",
  "Coordinador de Cuadrilla de Agua Potable B",
  "Coordinador de Cuadrilla de Agua Potable C",
  "Coordinador Operativo",
  "Coordinador Técnico A",
  "Director de Agua Potable",
  "Director de Drenaje",
  "Gerente de Infraestructura y Patrimonio Hídrico",
  "Jefe de Limpieza y Desazolve",
  "Jefe de Mantenimiento Electromecánico",
  "Jefe de Mantenimiento Hidráulico",
  "Jefe de Mantenimiento Sanitario",
  "Jefe de Maquinaria y Equipo de Desazolve",
  "Jefe de Plantas Tratadoras de Agua Residual",
  "Jefede Pozos y Operación Hidráulica",
  "Oficial Albañil A",
  "Oficial Albañil B",
  "Operador de Maquinaria A",
  "Operador de Maquinaria B",
  "Operador de Maquinaria C",
  "Operador de Maquinaria D",
  "Operador de Maquinaria E",
  "Operador de Maquinaria F",
  "Operador de Maquinaria G",
  "Operador de Pipa A",
  "Operador de Pipa B",
  "Operador de Pipa C",
  "Operador de Pipa D",
  "Operador de Pozo A",
  "Operador de Pozo B",
  "Operador de Pozo C",
  "Operador de Pozo D",
  "Operador de Pozo E",
  "Operador de Pozo F",
  "Operador de Pozo G",
  "Operador de Pozo H",
  "Operador de Pozo I",
  "Operador de Pozo J",
  "Operador de PTAR A",
  "Operador de PTAR B",
  "Operador de PTAR C",
  "Operador de Vactor A",
  "Operador de Vactor B"],
      "Subdirección General Jurídica": ["Auxiliar Administrativo E",
  "Auxiliar de Subdirección General B",
  "Coordinador de Asuntos Laborales",
  "Coordinador de Programa Institucional",
  "Coordinador de Verificación",
  "Jefe de Archivo",
  "Jefe de Asuntos Jurídicos",
  "Subdirector General Jurídica",
  "Verificador A",
  "Verificador B",
  "Verificador C",
  "Verificador D"],
      "Subdirección General de Planeación y Proyectos Estratégicos": ["Auxiliar de Calidad de Agua Potable (Potabilización)",
  "Auxiliar de Calidad de Agua Residual",
  "Auxiliar de Espacio Cultura del Agua",
  "Auxiliar de Proyectos",
  "Auxiliar de Subdirección General A",
  "Coordinador de Calidad de Agua",
  "Coordinador de Espacios de Cultura de Agua",
  "Coordinador de Licitación y Supervisión de Proyectos de Agua Potable",
  "Coordinador de Licitación y Supervisión de Proyectos de Drenaje",
  "Coordinador de Topografía y Catastro",
  "Jefe de Estudios y Proyectos de Agua Potable y Redes de Alcantarillado",
  "Jefe de Gestión Ambiental",
  "Subdirector General de Planeación y Proyectos Estratégicos"],
      "Órgano Interno de Control": [  "Auditor Financiero",
        "Auditor Técnico",
        "Autoridad Investigadora",
        "Autoridad Resolutoria",
        "Autoridad Substanciadora",
        "Coordinador de Control Interno y Evaluación de Desempeño",
        "Titular de Órgano Interno de Control"]
    };
function iniciarCatalogo(departamentoId, puestoId) {
    const departamentoSelect = document.getElementById(departamentoId);
    const puestoSelect = document.getElementById(puestoId);
    if (!departamentoSelect || !puestoSelect) {
        return;
    }
    Object.keys(window.catalogoPuestos).forEach(dep => {
        const option = document.createElement('option');
        option.value = dep;
        option.textContent = dep;
        departamentoSelect.appendChild(option);
    });
    departamentoSelect.addEventListener('change', () => {
        const puestos = window.catalogoPuestos[departamentoSelect.value] || [];
        puestoSelect.innerHTML = '<option value="">Seleccione un puesto</option>';
        puestos.forEach(puesto => {
            const opt = document.createElement('option');
            opt.value = puesto;
            opt.textContent = puesto;
            puestoSelect.appendChild(opt);
        });
    });
}

// Ejecutar la inicialización inmediatamente ya que este script se carga al
// final de la página y el evento DOMContentLoaded ya ocurrió.
iniciarCatalogo('departamento', 'puesto');
iniciarCatalogo('edit_departamento', 'edit_puesto');
